### ISSUE TITLE
do not work with a bug

### ISSUE THREAD

**Issue by superowner** [danielshervheim/unity-cloth-simulation#1]
Compute shader (ClothCompute(Clone)): Property (sphereBuffer) at kernel index (2) is not set
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
ClothSpawner:UpdateSimulation(Int32, Single) (at Assets/New Folder/Assets/Cloth/Scripts/ClothSpawner.cs:247)
ClothSpawner:FixedUpdate() (at Assets/New Folder/Assets/Cloth/Scripts/ClothSpawner.cs:255)

**Comment by danielshervheim** [comment]
This is because the sphere collider buffer is null which the compute shader is not expecting. As a temporary work-around, either:
A. Click on the Cloth prefab in the scene view, and under the "Sphere Colliders" foldout menu add at least one.
B. Open [ClothCompute.cs](https://github.com/danielshervheim/Cloth-Simulation/blob/master/Assets/Cloth/Resources/ClothCompute.compute#L265) and comment out lines 265-276.
